repos:
  - repo: local
    hooks:

      - id: autopep8
        name: autopep8 (system)
        entry: python -m autopep8 --in-place --aggressive 
        language: system
        types: [python]
        stages: [pre-commit]


      - id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [python]
        stages: [pre-commit]

      - id: run-pytest
        name: Run pytest
        entry: pytest -q
        language: system
        pass_filenames: false
        stages: [pre-commit]